# Generated by Django 3.2.6 on 2022-04-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220402_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidmalaysiakinicontent',
            name='pubDate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
