# Generated by Django 3.2.6 on 2022-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_covidmalaysiakinicontent_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidgooglenewscontent',
            name='pubDate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
