# Generated by Django 3.2.6 on 2022-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_covidgooglenewscontent_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidcontent',
            name='pubDate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
