# Generated by Django 3.2.6 on 2022-04-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryContent',
            new_name='Inventory',
        ),
        migrations.RenameModel(
            old_name='SupplierContent',
            new_name='Supplier',
        ),
    ]
