# Generated by Django 3.2.6 on 2022-04-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
